version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: >
      sh -c "
        ollama serve &
        until curl -fsS http://127.0.0.1:11434/api/tags >/dev/null 2>&1; do
          echo '⏳ Waiting for Ollama server...'
          sleep 5
        done
        echo '⬇️ Pulling gemma:2b...'
        ollama pull gemma:2b || true
        wait -n
      "
    restart: unless-stopped

  travel_assistant:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: travel_assistant
    depends_on:
      ollama:
        condition: service_started
    ports:
      - "8000:8000"                        # backend available at localhost:8000 on host
    env_file:
      - ./backend/.env
    environment:
      - LLM_API_URL=http://ollama:11434/api/generate
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: travel_frontend
    depends_on:
      travel_assistant:
        condition: service_healthy
    ports:
      - "3000:3000"                        # frontend available at localhost:3000 on host
    environment:
      # Used by browser code (outside docker, user’s machine)
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      # Used by server-side rendering inside the frontend container
      - API_URL_SERVER=http://travel_assistant:8000
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    restart: unless-stopped

volumes:
  ollama_models:
